### ISSUE TITLE
what is this package for?

### ISSUE THREAD

**Issue by jeannotes** [tigerk0430/lidar_closest_distance_detector#1]
Hi , it is amazing , but what is this for? any papers ?

**Comment by gyubeomim** [comment]
It doesn't have a concrete reason for :-) 

I also want to publish it to a paper but as you can see my codes, It has nothing special contribution. 

You can use it when you're using a LiDAR sensor and deal with any closest obstacles. Enjoy!

**Comment by gyubeomim** [comment]
close issue due to I gave an answer.

**Comment by jeannotes** [comment]
@edward0im really appreciate if you write more about your algorithm
